@startuml

title Диаграмма 1. Успешное получение данных о доступных продуктах (каждые 15 мин)

participant "core-app" as CoreApp
participant "ins-product-aggregator" as InsProductAggregator
collections "api-insurance-company" as ApiInsuranceCompany

autonumber

CoreApp -> InsProductAggregator: запрос о доступных продуктах
activate CoreApp
rnote over CoreApp : ожидание ответа

activate InsProductAggregator

loop по 5 страховым комания
    InsProductAggregator -> ApiInsuranceCompany: запрос о продуктах
    rnote over InsProductAggregator : ожидание ответа
    InsProductAggregator <-- ApiInsuranceCompany: успешный ответ на запрос о продуктах
end
InsProductAggregator -> InsProductAggregator: агрегация данных
CoreApp <-- InsProductAggregator: успешный ответ на запрос о доступных продуктах
deactivate InsProductAggregator
deactivate CoreApp


@enduml