apiVersion: apps/v1
kind: Deployment
metadata:
 name: testapp
 labels:
   app: testapp
spec:
 replicas: 1
 selector:
   matchLabels:
     pod: testapp-container
 template:
   metadata:
     labels:
       pod: testapp-container
   spec:
     containers:
     - name: testapp
       image: shestera/scaletestapp
       ports:
       - containerPort: 8080
       resources:
         requests:
           memory: "30Mi"
         limits:
           memory: "30Mi"
